# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
mod_version=1.2.1

assetmover_version=2.5
jei_version=4.15.0.268
# v3.3.2
fluidlogged_api_version=8212243
# v1.0.0
ocean_api_version=8426139
